# Tasca M3 T01
## Allison Garces Castaño

In [78]:
import numpy as np

### Ejercicio 1
Crea una función que dado un Array de una dimensión, te haga un resumen estadístico básico de los datos. Si detecta que el array tiene más de una dimensión, debe mostrar un mensaje de error.

In [79]:
d = np.random.randn(5,6) *5
d

array([[  0.34185544,   8.30710694,  -1.28172328, -12.25033852,
          2.51100246,  -1.57776509],
       [ -4.91369936,  -7.70149887,   2.15694144,   0.4121719 ,
          4.76752464,   2.7210103 ],
       [ -2.74664502,  -0.59265659,  10.41115786,   4.38560621,
          7.91241878,   4.58029897],
       [ -4.84246412,   0.02160125,   1.00851603,   7.51231443,
          5.41626333,  -3.12694179],
       [ -4.45053744,  -8.55214447,   0.34919774,   8.92558659,
          6.85451234,  -0.24237739]])

In [80]:
#Media Aritmetica

np.mean(d)

0.8772098236056753

In [81]:
#Media aritmetica de cada columna

np.mean(d, 0)

array([-3.3222981 , -1.70351835,  2.52881796,  1.79706812,  5.49234431,
        0.470845  ])

In [82]:
#Mediana

np.median(d)

0.3806848199521655

In [83]:
#Mediana aritmetica de cada columna

np.median(d, 0)

array([-4.45053744, -0.59265659,  1.00851603,  4.38560621,  5.41626333,
       -0.24237739])

In [84]:
#Desviación típica
np.std(d)

5.427893301944359

In [85]:
#Varianza

np.var(d) 

29.46202569729244

In [86]:
#Moda

stats.mode(d)

ModeResult(mode=array([[ -4.91369936,  -8.55214447,  -1.28172328, -12.25033852,
          2.51100246,  -3.12694179]]), count=array([[1, 1, 1, 1, 1, 1]]))

In [87]:
#Correlaccion

np.corrcoef(d)

array([[ 1.        , -0.41344317, -0.26589069, -0.4494626 , -0.73140168],
       [-0.41344317,  1.        ,  0.85333209,  0.42160616,  0.78349683],
       [-0.26589069,  0.85333209,  1.        ,  0.51703252,  0.61915135],
       [-0.4494626 ,  0.42160616,  0.51703252,  1.        ,  0.78432176],
       [-0.73140168,  0.78349683,  0.61915135,  0.78432176,  1.        ]])

In [88]:
#Calculando la correlación entre dos vectores.

np.corrcoef(d[0], d[1])

array([[ 1.        , -0.41344317],
       [-0.41344317,  1.        ]])

### Ejercicio 2
Crea una función que genere un cuadrado NxN de números aleatorios entre el 0 y el 100.

In [89]:
a = np.random.randint(0,100, size=(3,5))
print(a)

[[38 80 40 81 76]
 [54 34 36 41 11]
 [57 90  0 34 99]]


### Ejercicio 3
Crea una función que dada una tabla de dos dimensiones (NxM), te calcule los totales por fila y los totales por columna.

In [90]:
a = np.random.randint(5,50, size=(4,5))
print(a)

print("El resultado de la suma de columnas es: ", np.apply_along_axis(sum, 0, a))
print("El resultado de la suma de filas es: ", np.apply_along_axis(sum, 1, a))

[[42  7  9 13 15]
 [38 32 16 49 12]
 [ 7  9 19 21 29]
 [24 27 32 41 17]]
El resultado de la suma de columnas es:  [111  75  76 124  73]
El resultado de la suma de filas es:  [ 86 147  85 141]


### Ejercicio 4

Implementa manualmente una función que calcule el coeficiente de correlación. Infórmate sobre sus usos e interpretación.

In [91]:
altura = np.array([1.61, 1.73, 1.49], dtype=float)
peso = np.array([53, 79, 48], dtype=float)

corr = np.corrcoef(altura, peso)
print(corr)

[[1.         0.93130474]
 [0.93130474 1.        ]]
