# Tasca M3 T01
## Allison Garces Castaño

In [7]:
#Importaciones.

import numpy as np
from scipy import stats as st

### Ejercicio 1
Crea una función que dado un Array de una dimensión, te haga un resumen estadístico básico de los datos. Si detecta que el array tiene más de una dimensión, debe mostrar un mensaje de error.

In [9]:
def array(arr):
    
    print("Resumen estadistico basico de datos:\n", arr)
    
    print("La media es: ", np.mean(arr))
    print("La mediana es: ", np.median(arr))
    print("La desviacion tipica es: ", np.std(arr))
    print("La variancia es: ", np.var(arr))

    print("La correlacion es: ", np.corrcoef(arr))
    print("La moda es: ", st.mode(arr))
    
    if arr.ndim > 1:
        print("¡ERROR! No puede tener mas de una dimension para este analisis, total:", arr.ndim)
                                                    
    return np.array(arr)

arr = np.random.randint(0,50, size=(20))

"""arr = np.random.randint(0,50, size=(3,4)) 
    COMPROBACION PARA EL IF.
"""
resultado = array(arr)



Resumen estadistico basico de datos:
 [29 18 34 44 36 11 38  1 38 40  9 13 18 46 39 24 25 31 35 27]
La media es:  27.8
La mediana es:  30.0
La desviacion tipica es:  12.315031465652048
La variancia es:  151.66000000000003
La correlacion es:  1.0
La moda es:  ModeResult(mode=array([18]), count=array([2]))


### Ejercicio 2
Crea una función que genere un cuadrado NxN de números aleatorios entre el 0 y el 100.

In [11]:
def array(arr):
    
    return print(np.array(arr))

arr = np.random.randint(0,100, size=(3,5))
resultado = array(arr)

[[23  9 51 20 30]
 [43 25 72 43 83]
 [36 69 78 90 32]]


### Ejercicio 3
Crea una función que dada una tabla de dos dimensiones (NxM), te calcule los totales por fila y los totales por columna.

In [17]:
def array(arr):
    
    print("El resultado de la suma de columnas es: ", np.apply_along_axis(sum, 0, arr))
    print("El resultado de la suma de filas es: ", np.apply_along_axis(sum, 1, arr))
    
    return print("Array sumada:\n",np.array(arr))

arr = array(np.random.randint(5,50, size=(4,5)))
#resultado = array(arr)



El resultado de la suma de columnas es:  [143 109  98 129  93]
El resultado de la suma de filas es:  [138 141 144 149]
Array sumada:
 [[45 11 22 29 31]
 [20 40 47 10 24]
 [38 43 16 41  6]
 [40 15 13 49 32]]


### Ejercicio 4

Implementa manualmente una función que calcule el coeficiente de correlación. Infórmate sobre sus usos e interpretación.

In [18]:
def array(altura,peso):
    
    corr = np.corrcoef(altura, peso)
    
    return print(corr)

array(np.array([1.61, 1.73, 1.49], dtype=float),np.array([53, 79, 48], dtype=float))

[[1.         0.93130474]
 [0.93130474 1.        ]]
